services:
  deno-app:
    image: denoland/deno:latest
    container_name: deno-app
    environment:
      - DENO_ENV=development
    command: [ "run", "-A", "/app/main.ts" ]
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
